In [87]:
import pandas as pd

# Chargement des données
df_clients = pd.read_csv('Données+clients+VertigGo.csv')
df_ets = pd.read_csv('Données+entreprise+VertiGo.csv')

In [88]:
df_clients.head()

,ID_Client,âge,genre,type de voyage,destination,saison de voyage,durée de voyage (en jours),nombre de personnes,prix total,mode de paiement,évaluation sur 5,date de début de voyage,date de fin de voyage,période de voyage,budget_voyage_annuel,durée moyenne de voyage annuelle (en jours)
0,1,32,M,Culturel,NaN,été,10,2,4425,Virement,3,07-12-2023,09-12-2023,07-12-2023 au 09-12-2023,6407,4.0
1,2,38,Autre,détente,Népal,printemps,11,1,5743,Carte de crédit,2,01-09-2023,03-09-2023,01-09-2023 au 03-09-2023,4226,20.0
2,3,39,Autre,détente,Norvège,hiver,15,2,9565,Virement,3,22-02-2024,23-02-2024,22-02-2024 au 23-02-2024,5144,5.0
3,4,49,Autre,Aventure,Japon,printemps,16,2,9833,Virement,2,31-08-2023,03-09-2023,31-08-2023 au 03-09-2023,4307,19.0
4,5,23,M,Aventure,Islande,été,8,4,2358,Paypal,3,29-08-2023,01-09-2023,29-08-2023 au 01-09-2023,4348,10.0

In [89]:
df_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 16 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   ID_Client                                    801 non-null    int64
 1   âge                                          801 non-null    int64
 2   genre                                        637 non-null    object
 3   type de voyage                               676 non-null    object
 4   destination                                  796 non-null    object
 5   saison de voyage                             801 non-null    object
 6   durée de voyage (en jours)                   801 non-null    int64
 7   nombre de personnes                          801 non-null    int64
 8   prix total                                   801 non-null    int64
 9   mode de paiement                             649 non-null    object
 10  évaluation sur 5                             801 non-null    int64
 11  date de début de voyage                      799 non-null    object
 12  date de fin de voyage                        799 non-null    object
 13  période de voyage                            799 non-null    object
 14  budget_voyage_annuel                         801 non-null    int64
 15  durée moyenne de voyage annuelle (en jours)  800 non-null    float64
dtypes: float64(1), int64(7), object(8)
memory usage: 100.3+ KB

In [90]:
df_clients[df_clients.duplicated()]

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

In [91]:
df_clients[df_clients['durée moyenne de voyage annuelle (en jours)'].isnull()]

,ID_Client,âge,genre,type de voyage,destination,saison de voyage,durée de voyage (en jours),nombre de personnes,prix total,mode de paiement,évaluation sur 5,date de début de voyage,date de fin de voyage,période de voyage,budget_voyage_annuel,durée moyenne de voyage annuelle (en jours)
800,798,46,Autre,NaN,France,été,7,4,2349,Carte de crédit,2,22-11-2024,20-12-2024,22-11-2024 au 20-12-2024,3908,NaN

In [92]:
col_quantit = ['âge', 'durée de voyage (en jours)', 'nombre de personnes', 'prix total', 'évaluation sur 5', 'budget_voyage_annuel', 'durée moyenne de voyage annuelle (en jours)']
# création fonction detect outliers 

def detect_outliers(df, feature):
    q1 = df[feature].quantile(0.25)
    q3 = df[feature].quantile(0.75)
    iqr = q3-q1
    out_bas = (q1 -2*iqr)
    out_haut = (q3 + 2*iqr)

    return [((df[feature] < out_bas) | (df[feature] > out_haut)), iqr, out_bas, out_haut]

for i in col_quantit:
    print(f"--- Outliers pour la colonne : {i} ---")
    outliers = df_clients[detect_outliers(df_clients, i)[0]]
    display(outliers)

--- Outliers pour la colonne : âge ---

,ID_Client,âge,genre,type de voyage,destination,saison de voyage,durée de voyage (en jours),nombre de personnes,prix total,mode de paiement,évaluation sur 5,date de début de voyage,date de fin de voyage,période de voyage,budget_voyage_annuel,durée moyenne de voyage annuelle (en jours)
36,36,350,Autre,Détente,Bali,hiver,6,3,906,Virement,4,12-08-2023,16-08-2023,12-08-2023 au 16-08-2023,5351,19.0
51,51,220,M,Culturel,France,été,13,4,8099,Virement,3,12-06-2023,16-06-2023,12-06-2023 au 16-06-2023,4065,9.0
76,76,4100,Autre,Détente,Japon,hiver,14,1,9063,Paypal,3,22-05-2023,23-05-2023,22-05-2023 au 23-05-2023,7692,7.0

--- Outliers pour la colonne : durée de voyage (en jours) ---

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

--- Outliers pour la colonne : nombre de personnes ---

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

--- Outliers pour la colonne : prix total ---

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

--- Outliers pour la colonne : évaluation sur 5 ---

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

--- Outliers pour la colonne : budget_voyage_annuel ---

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

--- Outliers pour la colonne : durée moyenne de voyage annuelle (en jours) ---

Empty DataFrame
Columns: [ID_Client, âge, genre, type de voyage, destination, saison de voyage, durée de voyage (en jours), nombre de personnes, prix total, mode de paiement, évaluation sur 5, date de début de voyage, date de fin de voyage, période de voyage, budget_voyage_annuel, durée moyenne de voyage annuelle (en jours)]
Index: []

In [93]:
df_clients.loc[df_clients['âge'] == 350, 'âge'] = 35
df_clients.loc[df_clients['âge'] == 220, 'âge'] = 22
df_clients.loc[df_clients['âge'] == 4100, 'âge'] = 41

In [94]:
df_clients.isnull().sum()

ID_Client                                        0
âge                                              0
genre                                          164
type de voyage                                 125
destination                                      5
saison de voyage                                 0
durée de voyage (en jours)                       0
nombre de personnes                              0
prix total                                       0
mode de paiement                               152
évaluation sur 5                                 0
date de début de voyage                          2
date de fin de voyage                            2
période de voyage                                2
budget_voyage_annuel                             0
durée moyenne de voyage annuelle (en jours)      1
dtype: int64

In [95]:
df_clients[df_clients.isnull().any(axis=1)]

,ID_Client,âge,genre,type de voyage,destination,saison de voyage,durée de voyage (en jours),nombre de personnes,prix total,mode de paiement,évaluation sur 5,date de début de voyage,date de fin de voyage,période de voyage,budget_voyage_annuel,durée moyenne de voyage annuelle (en jours)
0,1,32,M,Culturel,NaN,été,10,2,4425,Virement,3,07-12-2023,09-12-2023,07-12-2023 au 09-12-2023,6407,4.0
6,7,33,Autre,culturel,Népal,hiver,5,4,105,NaN,3,19-05-2023,22-05-2023,19-05-2023 au 22-05-2023,5333,4.0
9,10,34,M,NaN,Japon,hiver,10,3,4459,Paypal,1,13-06-2023,16-06-2023,13-06-2023 au 16-06-2023,3658,6.0
22,22,45,M,Détente,Bali,hiver,8,1,2383,NaN,1,18-01-2024,21-01-2024,18-01-2024 au 21-01-2024,7114,6.0
30,30,37,Autre,détente,NaN,automne,8,1,2387,Virement,2,03-08-2023,04-08-2023,03-08-2023 au 04-08-2023,4577,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,790,18,F,NaN,Brésil,été,15,4,9796,Virement,3,13-04-2024,13-05-2024,13-04-2024 au 13-05-2024,618,4.0
794,792,30,M,NaN,Maroc,printemps,7,2,2339,Virement,2,11-07-2024,21-07-2024,11-07-2024 au 21-07-2024,6356,12.0
795,793,38,NaN,NaN,Népal,été,7,2,2348,Virement,2,15-03-2025,27-03-2025,15-03-2025 au 27-03-2025,1456,8.0
799,797,24,NaN,aventure,Islande,hiver,10,5,5736,Virement,3,14-04-2024,11-05-2024,14-04-2024 au 11-05-2024,5031,28.0
800,798,46,Autre,NaN,France,été,7,4,2349,Carte de crédit,2,22-11-2024,20-12-2024,22-11-2024 au 20-12-2024,3908,NaN

In [96]:
values = {}

for c in df_clients.columns:
    if df_clients[c].dtype != 'object':
        values[c] = df_clients[c].median()
    else :
        values[c] = df_clients[c].mode()[0]

df_clients.fillna(value=values, inplace=True)

In [97]:
df_clients.isnull().sum()

ID_Client                                      0
âge                                            0
genre                                          0
type de voyage                                 0
destination                                    0
saison de voyage                               0
durée de voyage (en jours)                     0
nombre de personnes                            0
prix total                                     0
mode de paiement                               0
évaluation sur 5                               0
date de début de voyage                        0
date de fin de voyage                          0
période de voyage                              0
budget_voyage_annuel                           0
durée moyenne de voyage annuelle (en jours)    0
dtype: int64

In [98]:
df_clients.groupby('type de voyage')['âge'].mean()

type de voyage
Aventure    35.401575
Culturel    33.554264
Détente     34.682692
aventure    34.342857
culturel    33.972222
détente     35.070707
Name: âge, dtype: float64

In [99]:
df_clients['type de voyage'] = df_clients['type de voyage'].str.lower()

In [100]:
df_clients.groupby('type de voyage')['âge'].mean()

type de voyage
aventure    34.922414
culturel    33.677596
détente     34.871921
Name: âge, dtype: float64

In [101]:
df_ets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    800 non-null    object
 1   Nombre_de_Clients       800 non-null    int64
 2   Revenu_des_Ventes       800 non-null    int64
 3   Depenses_Publicitaires  800 non-null    int64
 4   Nombre_de_Reservations  800 non-null    int64
dtypes: int64(4), object(1)
memory usage: 31.4+ KB

In [102]:
df_ets[df_ets.duplicated()]

Empty DataFrame
Columns: [Date, Nombre_de_Clients, Revenu_des_Ventes, Depenses_Publicitaires, Nombre_de_Reservations]
Index: []

In [103]:
df_ets.isnull().sum()

Date                      0
Nombre_de_Clients         0
Revenu_des_Ventes         0
Depenses_Publicitaires    0
Nombre_de_Reservations    0
dtype: int64

In [104]:
ets_col_quantit = ['Nombre_de_Clients', 'Revenu_des_Ventes', 'Depenses_Publicitaires', 'Nombre_de_Reservations']

for i in ets_col_quantit:
    print(f"--- Outliers pour la colonne : {i} ---")
    outliers = df_ets[detect_outliers(df_ets, i)[0]]
    print(f"IQR = {detect_outliers(df_ets, i)[1]}\nseuil bas = {detect_outliers(df_ets, i)[2]}\nseuil haut = {detect_outliers(df_ets, i)[3]}")
    display(outliers)

--- Outliers pour la colonne : Nombre_de_Clients ---
IQR = 14.0
seuil bas = 14.0
seuil haut = 84.0

,Date,Nombre_de_Clients,Revenu_des_Ventes,Depenses_Publicitaires,Nombre_de_Reservations
209,29/07/23,88,8693,5895,319

--- Outliers pour la colonne : Revenu_des_Ventes ---
IQR = 1364.0
seuil bas = 1528.75
seuil haut = 8348.75

,Date,Nombre_de_Clients,Revenu_des_Ventes,Depenses_Publicitaires,Nombre_de_Reservations
209,29/07/23,88,8693,5895,319

--- Outliers pour la colonne : Depenses_Publicitaires ---
IQR = 1294.25
seuil bas = 1787.5
seuil haut = 8258.75

Empty DataFrame
Columns: [Date, Nombre_de_Clients, Revenu_des_Ventes, Depenses_Publicitaires, Nombre_de_Reservations]
Index: []

--- Outliers pour la colonne : Nombre_de_Reservations ---
IQR = 69.0
seuil bas = 78.0
seuil haut = 423.0

Empty DataFrame
Columns: [Date, Nombre_de_Clients, Revenu_des_Ventes, Depenses_Publicitaires, Nombre_de_Reservations]
Index: []